SUBROUTINE AVERAGE(ARR, SIZE, VALUE)
    IMPLICIT NONE
    INTEGER:: SIZE, COUNT
    REAL, INTENT(OUT):: VALUE
    REAL, DIMENSION(SIZE):: ARR
    COUNT = 1
    VALUE = 0
!f2py intent(in) size
!f2py depend(size) arr

100 IF (COUNT.LE.SIZE) THEN
        VALUE = VALUE + ARR(COUNT)
        COUNT = COUNT + 1
        GOTO 100
    ENDIF
    VALUE = VALUE / SIZE
    RETURN
END SUBROUTINE AVERAGE